Cause panic.
    $ ~/roc/roc database.roc
    thread 'main' panicked at crates/compiler/gen_llvm/src/llvm/build.rs:5582:19:
    Error in alias analysis: error in module ModName("UserApp"), function definition FuncName("\x0f\x00\x00\x00\x1f\x00\x00\x006\xb7\xa8\xd7\x8cT\xc2\x99"), definition of value binding ValueId(11): could not find func in module ModName("UserApp") with name FuncName("\t\x00\x00\x00\x7f\x00\x00\x00\xa1\x891\xed\xc6\xf9\x823")
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

    $ ~/roc/roc version
    roc nightly pre-release, built from commit d73ea109 on Tue 09 Sep 2025 09:02:08 AM UTC